site_name: NKS Naren Kubernetes Solutions
site_url: https://naren4b.github.io/nks/
repo_name: "naren4b/nks"
repo_url: "https://github.com/naren4b/nks"
theme:
  name: material
  logo: https://avatars.githubusercontent.com/u/3488520?s=48&v=4
  language: en
  features:
    - toc.integrate
    - navigation.right
    - search.suggest
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
plugins:
  - search
  - social

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  analytics:
    provider: google
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/naren4b
    - icon: fontawesome/brands/twitter
      link: https://x.com/Narentwtr
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/narendranathpanda/

copyright: |
  &copy; 2024 <a href="https://github.com/naren4b"  target="_blank" rel="noopener">Narendranath Panda</a>
