site_name: NKS Naren Kubernetes Solutions
repo_name: "naren4b/nks"
repo_url: "https://github.com/naren4b/nks"
# theme:
#   name: material

nav:
  - Home: index.md
  - About: about.md
theme:
  name: readthedocs
  language: en
  features:
    - toc.integrate
    - navigation.right
    - search.suggest
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
plugins:
  - search
  - table-reader
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - tables
extra:
  analytics:
    provider: google

copyright: |
  &copy; 2024 <a href="https://github.com/naren4b"  target="_blank" rel="noopener">Narendranath Panda</a>
