# kubectl create secret generic keycloak-tls \
#         --from-file tls.key=keycloak.key \
#         --from-file tls.crt=keycloak.crt \
#         --from-file ca.crt=ca.crt \
#         --dry-run=client -o yaml
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJV==
kind: Secret
metadata:
  creationTimestamp: null
  name: keycloak-tls
