# kubectl create secret generic keycloak-db-secret   --from-literal=username=naren   --from-literal=password=naren123
apiVersion: v1
data:
  password: bmFyZW4xMjM= 
  username: bmFyZW4=
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: default
type: Opaque